// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ConsecutiveTransfer { from_id: string, to_id: string, from: string, to: string, }