// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Approval } from './Approval';
import type { ApprovalForAll } from './ApprovalForAll';
import type { ConsecutiveTransfer } from './ConsecutiveTransfer';
import type { Transfer } from './Transfer';

export type ERC721 =
  | ({ type: 'Transfer' } & Transfer)
  | ({ type: 'Approval' } & Approval)
  | ({ type: 'ApprovalForAll' } & ApprovalForAll)
  | ({ type: 'ConsecutiveTransfer' } & ConsecutiveTransfer);
