// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ERC1155 } from './erc1155/ERC1155';
import type { ERC20 } from './erc20/ERC20';
import type { ERC721 } from './erc721/ERC721';
import type { Native } from './native/Native';

export interface AssetChanges {
  erc20: Record<string, Array<ERC20>>;
  erc721: Record<string, Array<ERC721>>;
  erc1155: Record<string, Array<ERC1155>>;
  native: Array<Native>;
}
