// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetChanges } from './AssetChanges';
import type { Revert } from './Revert';

export type Simulation =
  | ({ type: 'Revert' } & Revert)
  | ({ type: 'Success' } & AssetChanges);
