// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetChanges } from "./AssetChanges";

export type Simulation = { type: "Revert" } & string | null | { type: "Success" } & AssetChanges;