/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Transaction to be simulated.
 */
export interface Transaction {
  /**
   * Data to send.
   *
   * This is a byte hex string prefixed with 0x.
   */
  data: string;
  /**
   * Address from.
   */
  from: string;
  /**
   * Address to.
   */
  to: string;
  /**
   * Value to send.
   */
  value: string;
  [k: string]: unknown;
}
