// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TransferSingle { operator: string, from: string, to: string, id: string, value: string, }